apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
images:
- name: tetris-devsecops
  newName: 997961584240.dkr.ecr.ap-southeast-1.amazonaws.com/devsecops/ecr
  newTag: 650fee6
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: tetris
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: tetris-staging.example.com
  target:
    kind: Ingress
    name: tetris
